hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
hystrix.command.default.execution.isolation.strategy: THREAD

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: book-store
          uri: lb://book-store
          predicates:
            - Path=/api/books/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - RewritePath=/api/(?<books>.*), /$\{books}
            - name: Hystrix
              args:
                name: booksFallbackCommand
                fallbackUri: forward:/fallback/books


        - id: movie-store
          uri: lb://movie-store
          predicates:
            - Path=/api/movies/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - RewritePath=/api/(?<movies>.*), /$\{movies}
            - AddResponseHeader=X-Some-Header, aboullaite.me


        - id: car-inventory
          #uri: lb://car-inventory
          uri: http://localhost:8010/api/cars/
          predicates:
            - Path=/api/cars/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - TokenRelay=
            - RewritePath=/api/(?<cars>.*), /$\{cars}

  redis:
    host: 172.17.0.2
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100

  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa
            #client-id: appclient
            #client-secret: appclient@123
            client-id: kelly
            client-secret: kelly@123
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read,write
        provider:
          uaa:
            authorization-uri: http://localhost:9050/oauth/authorize
            token-uri: http://localhost:9050/oauth/token
            user-info-uri: http://localhost:9050/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9050/token_keys

server:
  port: 8887

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8888/eureka
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: hystrix.stream


logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG